datasets:
  dataset1:
    numeric_data: [10, 20, 30, 40]
    text_data: ["Отлично!", "Может быть лучше.", "Не хватает деталей."]
  dataset2:
    numeric_data: [5, 15, 25, 35]
    text_data: ["Хорошо", "Неплохо", "Может быть лучше."]
